baseURL = 'https://henrique-vc-silva.github.io/'
languageCode = 'pt-pt'
title = 'Henrique Silva'
theme = 'PaperMod'

[params]
  author = 'Henrique Silva'
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto" # dark, light, auto
  hideFooter = false
  description = 'Engenheiro Informático | Analista Criativo com Propósito'
  DateFormat = "02 Jan 2006"

[menu]
  [[menu.main]]
    name = "Sobre"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]
